system/urls.py
from django.contrib import admin
from django.conf.urls import url
from system.views import *
urlpatterns=[
    url(r'^$|^login/$',login,name='login'),
    url(r'^login/Action/$',loginAction,name='loginAction'),
    url(r'^logout$',logoutAction,name='logout'),
    url(r'^change/$',changePassword,name='changePassword'),
    url(r'^change/Action/$',changeAction,name='changePasswordAction'),
    url(r'^change/Action/(\d{1})/$',sorted,name='sortedChange'),
    url(r'^delete/$',delete,name='delete'),
    url(r'^search/$',search,name='search'),
    url(r'^add/$',add,name='add'),
    url(r'^change/(?P<studentID>[0-9]+)/$',change,name='change'),
    url(r'^ACaction/$',ACaction,name='ACaction'),
    url(r'^divided/$',divided,name='divided'),
]

webExercise/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include,url
from system import urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(urls,namespace='system'))
]

system/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    StudentID=models.CharField(primary_key=True,max_length=20)
    Name=models.CharField(max_length=20)
    Chinese=models.FloatField(max_length=5,default=0)
    Math=models.FloatField(max_length=5,default=0)
    English=models.FloatField(max_length=5,default=0)
    Physics=models.FloatField(max_length=5,default=0)
    Chemistry=models.FloatField(max_length=5,default=0)
    password=models.CharField(max_length=20)
    sum=models.FloatField(max_length=5,default=0)
    def __str__(self):
        return self.StudentID

class Teacher(models.Model):
    TeacherID=models.CharField(primary_key=True,max_length=20)
    Name=models.CharField(max_length=20)
    password=models.CharField(max_length=20)
    def __str__(self):
        return self.TeacherID

system/views.py
#coding=UTF-8
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from system.models import *
# Create your views here.

def login(request):
    return render(request,'system/login.html')


def loginAction(request):
    if request.method=='POST':
        ID = request.POST.get('ID').strip()
        Password = request.POST.get('Password').strip()
        if request.POST.get('select')=='0':
            if Student.objects.filter(StudentID=ID):
                student=Student.objects.get(pk=ID)
                if Password==student.password:
                    request.session['studentID']=ID
                    lst=list(Student.objects.order_by('-sum'))
                    Ranking=lst.index(Student.objects.get(pk=ID))+1
                    return render(request,'system/student.html',{'student_score': student,'Ranking':Ranking})
                else:
                    return render(request,'system/login.html',{'error':'你输入的密码错误'})
            else:
                return HttpResponse('没有这个用户！')
        else:
            if Teacher.objects.filter(TeacherID=ID):
                teacher=Teacher.objects.get(pk=ID)
                if Password==teacher.password:
                    request.session['teacherID']=ID
                    students=Student.objects.order_by('-sum')
                    teacher=Teacher.objects.get(pk=ID)
                    return render(request,'system/teacher.html',{'students':students,'teacher':teacher,'subject':'排名(按总分排名）'})
                else:
                    return render(request, 'system/login.html', {'error': '你输入的密码错误'})
            else:
                return HttpResponse('没有这个用户！')
    raise Http404



def changePassword(request):
    try:
        ID=request.session['studentID']
        return render(request, 'system/changePassword.html')
    except:
        raise Http404

def changeAction(request):
    try:
        ID = request.session['studentID']
        if request.method=='POST':
            Password=request.POST['newPassword']
            RepeatPassword=request.POST['repeatPassword']
            if Password==RepeatPassword:
                ID=request.session['studentID']
                del request.session['studentID']
                student=Student.objects.get(pk=ID)
                student.password = Password
                student.save()
                Student.objects.get(pk=ID).save()
                return redirect('/login/')
            else:
                return HttpResponse('两次输入的密码不相同，请重新确认！')
        else:
            return HttpResponse('只支持post请求')
    except:
        raise Http404


def logoutAction(request):
    try:
        del request.session['studentID']
        return redirect('login/')
    except KeyError:
        del request.session['teacherID']
        return redirect('login/')
    except:
        raise Http404

def sorted(request,subjectID):
    try:
        ID = request.session['teacherID']
        teacher = Teacher.objects.get(pk=ID)
        if subjectID=='0':
            students = Student.objects.order_by('-sum')
            return render(request, 'system/teacher.html', {'students': students, 'teacher': teacher,'subject':'排名(按总分排名）'})
        elif subjectID=='1':
            students = Student.objects.order_by('-Chinese')
            return render(request, 'system/teacher.html', {'students': students, 'teacher': teacher,'subject':'排名(按语文排名）'})
        elif subjectID=='2':
            students = Student.objects.order_by('-Math')
            return render(request, 'system/teacher.html', {'students': students, 'teacher': teacher,'subject':'排名(按数学排名）'})
        elif subjectID=='3':
            students = Student.objects.order_by('-English')
            return render(request, 'system/teacher.html', {'students': students, 'teacher': teacher,'subject':'排名(按英语排名）'})
        elif subjectID=='4':
            students = Student.objects.order_by('-Physics')
            return render(request, 'system/teacher.html', {'students': students, 'teacher': teacher,'subject':'排名(按物理排名）'})
        elif subjectID=='5':
            students = Student.objects.order_by('-Chemistry')
            return render(request, 'system/teacher.html', {'students': students, 'teacher': teacher,'subject':'排名(按化学排名）'})
        else:
            raise Http404
    except:
        raise Http404


def delete(request):
    try:
        ID = request.session['teacherID']
        teacher = Teacher.objects.get(pk=ID)
        lst=request.POST.getlist('selected_student')
        for studentID in lst:
            Student.objects.get(pk=studentID).delete()
        students = Student.objects.order_by('-sum')
        return render(request, 'system/teacher.html', {'students': students, 'teacher': teacher, 'subject': '排名(按总分排名）'})
    except:
        raise Http404



def search(request):
    try:
        ID = request.session['teacherID']
        teacher = Teacher.objects.get(pk=ID)
        content=request.POST.get('search')
        if list(Student.objects.filter(StudentID__icontains=content))!=[]:
            students=Student.objects.filter(StudentID__icontains=content)
            return render(request,'system/teacher.html',{'students': students, 'teacher': teacher})
        elif list(Student.objects.filter(Name__icontains=content))!=[]:
            students=list(Student.objects.filter(Name__icontains=content))
            return render(request,'system/teacher.html',{'students': students, 'teacher': teacher})
        else:
            return HttpResponse('搜索无结果')
    except:
        raise Http404



def change(request,studentID):
    try:
        ID = request.session['teacherID']
        student=Student.objects.get(pk=studentID)
        return render(request,'system/ACStudent.html',{'student':student})
    except:
        raise Http404


def add(request):
    try:
        ID = request.session['teacherID']
        return render(request,'system/ACStudent.html')
    except:
        raise Http404


def ACaction(request):
    try:
        teacherID = request.session['teacherID']
        ID=request.POST.get('studentID')
        Name=request.POST.get('Name')
        Chinese=request.POST.get('Chinese')
        Math=request.POST.get('Math')
        English=request.POST.get('English')
        Physics=request.POST.get('Physics')
        Chemistry=request.POST.get('Chemistry')
        Password=request.POST.get('Password')
        try:
            student=Student.objects.get(pk=ID)
        except ObjectDoesNotExist:
            student=Student()
        except:
            return Http404
        student.StudentID=ID
        student.Name = Name
        student.Chinese = Chinese
        student.Math = Math
        student.English = English
        student.Physics = Physics
        student.Chemistry = Chemistry
        student.sum=float(Chinese)+float(Math)+float(English)+float(Physics)+float(Chemistry)
        student.password=Password
        student.save()
        return redirect('/change/Action/0/')
    except:
        raise Http404


def divided(request):
    try:
        ID = request.session['teacherID']
        teacher = Teacher.objects.get(pk=ID)
        start=request.POST.get('start')
        end=request.POST.get('end')
        subject=request.POST.get('subject')
        students = Student.objects.order_by('-' + subject)
        chooseStudent = []
        if subject=='Chinese':
            for student in students:
                if float(student.Chinese)>=float(start) and float(student.Chinese)<float(end):
                    chooseStudent.append(student)
            return render(request, 'system/teacher.html',{'students': chooseStudent, 'teacher': teacher, 'subject': '排名(按语文排名）','start':start,'end':end})
        elif subject=='Math':
            for student in students:
                if float(student.Math)>=float(start) and float(student.Math)<float(end):
                    chooseStudent.append(student)
            return render(request, 'system/teacher.html',{'students': chooseStudent, 'teacher': teacher, 'subject': '排名(按数学排名）','start':start,'end':end})
        elif subject=='English':
            for student in students:
                if float(student.English)>=float(start) and float(student.English)<float(end):
                    chooseStudent.append(student)
            return render(request, 'system/teacher.html',{'students': chooseStudent, 'teacher': teacher, 'subject': '排名(按英语排名）','start':start,'end':end})
        elif subject=='Physics':
            for student in students:
                if float(student.Physics)>=float(start) and float(student.Physics)<float(end):
                    chooseStudent.append(student)
            return render(request, 'system/teacher.html',{'students': chooseStudent, 'teacher': teacher, 'subject': '排名(按物理排名）','start':start,'end':end})
        elif subject=='Chemistry':
            for student in students:
                if float(student.Chemistry)>=float(start) and float(student.Chemistry)<float(end):
                    chooseStudent.append(student)
            return render(request, 'system/teacher.html',{'students': chooseStudent, 'teacher': teacher, 'subject': '排名(按化学排名）','start':start,'end':end})
        else:
            for student in students:
                if float(student.sum) >= float(start) and float(student.sum) < float(end):
                    chooseStudent.append(student)
            return render(request, 'system/teacher.html', {'students': chooseStudent, 'teacher': teacher, 'subject':'排名(按总分排名）','start':start,'end':end})
    except:
        raise Http404

system/templates/system/ACStudent.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'system/ACStudent.css' %}" />
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="text-align: center;width: 100%;height: 100%;margin:0;">
<div class="header">
    <h5>学生成绩管理系统</h5>
    <br>
</div>
<form action="{% url 'system:ACaction' %}" method="post">
    {% csrf_token %}
    <label>
        学号
        <input type="text" name="studentID" required value="{{ student.StudentID }}" class="input" />
    </label>
    <br>
    <label>
        姓名
        <input type="text" name="Name" required value="{{ student.Name }}" class="input"/>
    </label>
    <br>
    <label>
        语文
        <input type="number" name="Chinese"  required value="{{ student.Chinese }}" class="input"/>
    </label>
    <br>
    <label>
        数学
        <input type="number" name="Math"  required value="{{ student.Math }}" class="input"/>
    </label>
    <br>
    <label>
        英语
        <input type="number" name="English"  required value="{{ student.English }}" class="input"/>
    </label>
    <br>
    <label>
        物理
        <input type="number" name="Physics" required  value="{{ student.Physics }}" class="input"/>
    </label>
    <br>
    <label>
        化学
        <input type="number" name="Chemistry"  required value="{{ student.Chemistry }}" class="input"/>
    </label>
    <br>
    <label>
        密码
        <input type="password" name="Password" value="123456" required class="input"/>
    </label>
    <br>
    <input type="submit" value="提交保存" class="submit">
</form>
<footer style="position: relative;color:rgb(27,66,254); ">
    <p>————————————————————————————————————————————————————————————————————————————————————</p>
    <p>管理员联系方式：18846188605</p>
</footer>
</body>
</html>

system/templates/system/changePassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'system/changePassword.css' %}" />
<head>
    <meta charset="UTF-8">
    <title>记录每一点进步</title>
</head>
<body id="webStyle">
{% if error %}<p><strong>{{ error }}</strong></p>{% endif %}
<br>
{% if changePassword %}<p><strong>{{ changePassword }}</strong></p>{% endif %}
<div id="login_form">
    <form action="{% url 'system:changePasswordAction' %}" method="post">
        {% csrf_token %}
        <label>
            <input type="password" name="newPassword" placeholder="新密码" class="inputStyle" />
        </label>
        <br>
        <label>
            <input type="password" name="repeatPassword" class="inputStyle" placeholder="请重复密码"/>
        </label>
        <br>
        <input type="submit" value="确认修改" id="submit" />
    </form>
</div>

</body>
</html>

system/templates/system/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'system/login.css' %}" />
<head>
    <meta charset="UTF-8">
    <title>记录每一点进步</title>
</head>
<body id="webStyle">
{% if error %}<p><strong>{{ error }}</strong></p>{% endif %}
<br>
{% if changePassword %}<p><strong>{{ changePassword }}</strong></p>{% endif %}
<div id="login_form">
    <form action="{% url 'system:loginAction' %}" method="post">
        {% csrf_token %}

        <br>
        <label>
            <input type="text" name="ID" autofocus class="inputStyle" placeholder="用户名称"/>
        </label>
        <br>
        <label>
            <input type="password" class="inputStyle" name="Password" placeholder="密码" />
        </label>
        <br>
        <label>
            选择用户类型
            <div class="selected">

                <select name="select"  >
                    <option value="0">
                        学生
                    </option>
                    <option value="1">
                        教师
                    </option>
                </select>
            </div>
        </label>
        <br>
        <input type="submit" id="submit" value="登录">
        <br>
        <!--<input type="button" class="submit"  value="登录">
        <input type="button" class="submit" style=" transform: rotate(180deg);" value="登录">  wait to be completed-->
    </form>
</div>

</body>
</html>

system/templates/system/student.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'system/student.css' %}" />
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="text-align: center;width: 100%;height: 100%;margin:0;">
<div class="header">
    <h5>学生成绩管理系统</h5>
    <p>你好！{{ student_score.Name }}同学</p>
    <form action="{% url 'system:logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="退出登录" id="logout" />
    </form>
</div>
<br>
<a href="{% url 'system:changePassword' %}" id="changePassword">< 修改密码</a>
<table id="scores">
    <caption style="font-weight: bolder;font-family:微软雅黑;font-size: 1.1em;">
        {{ student_score.Name }}的成绩
    </caption>
    <tbody>
    <tr class="headTable">
        <th>学号</th>
        <th>你的名字</th>
        <th>语文</th>
        <th>数学</th>
        <th>英语</th>
        <th>物理</th>
        <th>化学</th>
        <th>总分</th>
        <th>排名</th>
    </tr>
    <tr class="contentTable">
        <td>{{ student_score.StudentID }}</td>
        <td>{{ student_score.Name }}</td>
        <td>{{ student_score.Chinese }}</td>
        <td>{{ student_score.Math }}</td>
        <td>{{ student_score.English }}</td>
        <td>{{ student_score.Physics }}</td>
        <td>{{ student_score.Chemistry }}</td>
        <td>{{ student_score.sum }}</td>
        <td>{{ Ranking }}</td>
    </tr>
    </tbody>
</table>
<br>
<footer style="position: relative;color:rgb(27,66,254); ">
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <p>————————————————————————————————————————————————————————————————————————————————————</p>
    <p>管理员联系方式：18846188605</p>
</footer>
</body>
</html>

system/templates/system/teacher.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'system/teacher.css' %}" />
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="text-align: center;width: 100%;height: 100%;margin:0;">
<div class="header">
    <h5>学生成绩管理系统</h5>
    <p>你好！{{ teacher.Name }}老师</p>
    <form action="{% url 'system:logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="退出登录" id="logout" />
    <br>
</form>
</div>
<a href="/change/Action/0/"id="all_scores">< 所有学生成绩</a>
<form action="{% url 'system:search' %}" method="post">
    {% csrf_token %}
    <input type="text" autofocus placeholder="搜索学号或学生姓名" required name="search" class="input"/>
    <input type="submit" value="搜索" class="submit">
</form>
<form action="{% url 'system:divided' %}" method="post">
    {% csrf_token %}
    <label style="font-weight: bold">
        分数段查询
        <input type="number" required class="input" placeholder={{ start |default:'最低分'}} name="start">
    </label>
    <label style="font-weight: bold">
        ————
        <input type="number" required class='input' placeholder={{ end |default:'最高分'}} name="end">
    </label>
    <div class="selected">
        <select name="subject">
            <option value="Chinese" selected>
                语文
            </option>
            <option value="Math">
                数学
            </option>
            <option value="English">
                英语
            </option>
            <option value="Physics">
                物理
            </option>
            <option value="Chemistry">
                化学
            </option>
            <option value="sum">
                总分
            </option>
        </select>
    </div>
    <input type="submit" value="查询" class="submit">
</form>
<form action="{% url 'system:delete' %}" method="post">
    {% csrf_token %}
    <table id="scores">
        <caption>
            学生成绩
        </caption>
        <tbody>
        <tr class="headTable">
            <th></th>
            <th>学号</th>
            <th>你的名字</th>
            <th><a href="{% url 'system:sortedChange' '1' %}">语文</a></th>
            <th><a href="{% url 'system:sortedChange' '2' %}">数学</a></th>
            <th><a href="{% url 'system:sortedChange' '3' %}">英语</a></th>
            <th><a href="{% url 'system:sortedChange' '4' %}">物理</a></th>
            <th><a href="{% url 'system:sortedChange' '5' %}">化学</a></th>
            <th><a href="{% url 'system:sortedChange' '0' %}">总分</a></th>
            <th style="width: auto;">{{ subject }}</th>
            <th>
                <div>
                    <input type="submit" value="删除"  name="delete" class="submit"/>
                </div>
            </th>
        </tr>
        {% for student in students %}
        <tr class="contentTable">
            <td style="width: 1%;">{{ forloop.counter }}</td>
            <td><a href='/change/{{ student.StudentID }}'>{{ student.StudentID }}</a></td>
            <td>{{ student.Name }}</td>
            <td>{{ student.Chinese }}</td>
            <td>{{ student.Math }}</td>
            <td>{{ student.English }}</td>
            <td>{{ student.Physics }}</td>
            <td>{{ student.Chemistry }}</td>
            <td>{{ student.sum }}</td>
            <td>{{ forloop.counter }}</td>
            <td style="width: 1%;">
                <div>
                    <input type="checkbox" id="choose" name="selected_student" value={{ student.StudentID }} />
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</form>
<form method="post" action="{% url 'system:add' %}">
    {% csrf_token %}
    <input type="submit" value="添加学生" id="add" />
</form>
<footer style="position: relative;color:rgb(27,66,254); ">
    <br><br><br>
    <p>————————————————————————————————————————————————————————————————————————————————————</p>
    <p>管理员联系方式：18846188605</p>
</footer>
</body>
<script type="text/javascript">
   /* var box=document.getElementById('mainBox');
    box.onclick=function () {
        var boxes=document.getElementsByClassName('selected');
        if(box.checked){
            for ( var i=0;i<boxes.length;i++)
            {
                boxes[i].checked=true;
            }
        }
        else{
            for ( var j=0;j<boxes.length;j+=1)
            {
                boxes[j].checked=false;
            }
        }
    }*/
</script>
</html>